Repository GeeksCAT/hacktoberfest-web-2022, pull requests merged in 2022-10, with the labels that each got.

#3 feat: add the diary
  src/components/Sections/Diary.vue
  src/content.ts
  src/types.ts
Labels: HACKTOBERFEST-ACCEPTED

#4 ci: adds dockerfile
  Dockerfile
  docker/nginx.conf
  docker/run.sh
  tsconfig.json
Labels: HACKTOBERFEST-ACCEPTED

#5 feat: improve responsive design and add a button to go up
  README.md
  src/App.vue
  src/components/Atoms/ASection.vue
  src/components/Atoms/ATitle.vue
  src/components/Modules/MGoUp.vue
  src/components/Modules/MMenuOptions.vue
  src/components/Sections/Contact.vue
  src/components/Sections/Diary.vue
  src/components/Sections/Menu.vue
  src/components/Sections/Sponsors.vue
Labels: HACKTOBERFEST-ACCEPTED

#6 Feat/route
  src/App.vue
  src/components/Modules/MGoUp.vue
  src/components/Sections/CodeOfConduct.vue
  src/components/Sections/Footer.vue
  src/components/Sections/SCodeOfConduct.vue
  src/components/Sections/SContact.vue
  src/components/Sections/SDiary.vue
  src/components/Sections/SFooter.vue
  src/components/Sections/SIntro.vue
  src/components/Sections/SJoin.vue
  src/components/Sections/SMenu.vue
  src/components/Sections/SOrganizer.vue
  src/components/Sections/Sponsors.vue
  src/components/Sections/WhatWeWillDo.vue
  src/main.ts
  src/router.ts
  src/views/Home.vue
  src/views/NotFound.vue
Labels: HACKTOBERFEST-ACCEPTED

#8 feat: design modernized
  src/assets/images/logo-pythongirona.png
  src/components/Atoms/ABox.vue
  src/components/Atoms/ALink.vue
  src/components/Atoms/ATitle.vue
  src/components/Modules/MGoUp.vue
  src/components/Modules/MMenuOptions.vue
  src/components/Sections/SContact.vue
  src/components/Sections/SDiary.vue
  src/components/Sections/SIntro.vue
  src/components/Sections/SJoin.vue
  src/components/Sections/SMenu.vue
  src/content.ts
  tailwind.config.js
Labels: HACKTOBERFEST-ACCEPTED

#10 feat: adds a background of some sections
  src/assets/images/bg.jpg
  src/components/Sections/SIntro.vue
  src/components/Sections/SMenu.vue
Labels: HACKTOBERFEST-ACCEPTED

#11 Add supporters section
  CHANGELOG.md
  README.md
  src/assets/images/pyladies.png
  src/components/Sections/SCodeOfConduct.vue
  src/components/Sections/SOrganizers.vue
  src/components/Sections/SSupporters.vue
  src/content.ts
  src/types.ts
  src/views/Home.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#13 Start styling banner
  src/components/Sections/SIntro.vue
Labels: enhancement

#14 feat: set max width for big screens
  package-lock.json
  package.json
  src/components/Atoms/ASection.vue
  src/components/Atoms/ATitle.vue
  src/components/Modules/MLogosGallery.vue
  src/components/Sections/SCodeOfConduct.vue
  src/components/Sections/SContact.vue
  src/components/Sections/SIntro.vue
  src/components/Sections/SOrganizers.vue
  src/components/Sections/SSupporters.vue
  src/components/Sections/Sponsors.vue
  src/content.ts
  src/types.ts
Labels: HACKTOBERFEST-ACCEPTED

#16 Disable sponsors
  src/views/Home.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#17 fix: overflow added into the diary to improve the user experience in mobile device
  src/components/Sections/SDiary.vue
Labels: bug, HACKTOBERFEST-ACCEPTED

#18 Feat/hb link
  src/components/Sections/SIntro.vue
  src/components/Sections/WhatWeWillDo.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#21 Added the speakers section
  src/components/Atoms/ASection.vue
  src/components/Sections/SSpeakers.vue
  src/components/Sections/SWhatWeWillDo.vue
  src/content.ts
  src/types.ts
  src/views/Home.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#22 feat: enable the sponsors section
  src/assets/images/apsl.png
  src/assets/images/gisce.png
  src/assets/images/hipsotech.png
  src/assets/images/photopills.png
  src/content.ts
  src/views/Home.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#23 Feature/add ssg and airflow talks details
  src/components/Sections/SDiary.vue
  src/content.ts
Labels: enhancement
